version: '3'
services:
  db:
    image: 'postgres:13'
    container_name: 'scout_postgres'
    environment:
      POSTGRES_PASSWORD: 'pass123'
    ports:
      - '54320:5432'
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
